-- phpMyAdmin SQL Dump
-- version 4.8.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 27, 2020 at 02:52 AM
-- Server version: 10.1.31-MariaDB
-- PHP Version: 7.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `thietbi`
--

-- --------------------------------------------------------

--
-- Table structure for table `category`
--

CREATE TABLE `category` (
  `id` int(11) NOT NULL,
  `name` varchar(200) NOT NULL,
  `avatar` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `category`
--

INSERT INTO `category` (`id`, `name`, `avatar`) VALUES
(1, 'Điện thoại', 'https://photo2.tinhte.vn/data/attachment-files/2020/09/5161579_thay_doi_icon_app_ios9.jpg'),
(2, 'Labtop', 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ5RpCOYgh8HsUehGoFMJolq0DJYq71AGtbzw&usqp=CAU');

-- --------------------------------------------------------

--
-- Table structure for table `product`
--

CREATE TABLE `product` (
  `id` int(11) NOT NULL,
  `name` varchar(200) NOT NULL,
  `price` int(15) NOT NULL,
  `avatar` varchar(500) NOT NULL,
  `description` varchar(10000) NOT NULL,
  `categoryid` int(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `product`
--

INSERT INTO `product` (`id`, `name`, `price`, `avatar`, `description`, `categoryid`) VALUES
(1, 'Vsmart Active 3 6GB Ram', 3290000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/v/s/vsmart-active-3_2_.png', 'Vsmart Active 3 - Điện thoại giá rẻ thương hiệu Việt\r\nVsmart thuộc tập đoàn Vingroup là dòng điện thoại thương hiệu Việt đang ngày càng được đông đảo người dân quan tâm. Mới đây, hãng tiếp tục giới thiệu thêm nhiều mẫu smartphone mới như Vsmart  Live 3, Vsmart  Star 3... và Vsmart Active 3. Trong đó, Active 3 mang trong mình nhiều tính năng và cấu hình cao với mức giá vô cùng tốt.\r\n\r\nActive 3 sở hữu mặt lưng nhựa giả kính cao cấp cùng màn hình 6.39 inch tràn viền\r\nVsmart Active 3 mang trong mình một thiết kế bằng nhưa nhưng nhìn không khác những điện thoại bằng kính khác trên thị trường, đem lại cho người dùng cảm giác sang trọng, tinh tế khi sử dụng. Bên cạnh đó, mặt lưng kính của chiếc điện thọai này còn tỏ ra rất chắc chắn và bền bỉ khi có thể chống chịu các lực tác động bên ngoài khá tốt. Mặt lưng còn mang hiệu ứng chuyển màu rất thu hút.', 1),
(2, 'Samsung Galaxy Note 20 Ultra', 25700000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/b/l/black_final.jpg', 'Samsung Note 20 Ultra: Thiết kế sang trọng và nhiều công nghệ cực tốt\r\nSamsung là gã khổng lồ công nghệ cực kỳ nổi tiếng đến từ đất nước Hàn Quốc, mỗi chiếc điện thoại của hãng đều mang thiết kế hiện đại, sang trọng đi kèm với đa dạng công nghệ cực kỳ nổi bật. Note 20 Ultra là một trong những chiếc smartphone nổi tiếng và đang được nhiều người quan tâm, đón nhận. Samsung hứa hẹn sẽ chiều lòng khách hàng với thiết kế lộng lẫy, cùng với vô vàng công nghệ, chip xử lý mới mẻ, thật hiện đại. Ngoài ra, bạn cũng có thể tham khảo thêm Note 20 Ultra 5G.\r\n\r\nMàn hình AMOLED cực sống động kèm với hệ điều hành Android, One UI 2.1\r\nĐiều đầu tiên mà chắc hẳn nhiều người sẽ thích thú ở chiếc điện thoại Samsung Galaxy Note 20 Ultra đó chính là sự trang bị màn hình AMOLED. Với Dynamic AMOLED được trang bị lên đến 16M colors, kích thước màn hình lên đến 6.9 inches và độ phân giải Quad-HD+. Tạo ra mọi màu sắc chân thật nhất, sống động và sắc nét cho người dùng trải nghiệm thích thú. ', 1),
(3, 'Xiaomi Redmi Note 9 Pro', 5700000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/_/0/_0000_pms_1589425078.08482488.jpg', 'Điện thoại Xiaomi Redmi Note 9 Pro – Smartphone màn hình rộng, viên pin lớn\r\nCùng với Xiaomi Redmi Note 9s, Xiaomi Redmi Note 9 Pro là phiên bản nâng cấp của điện thoại Xiaomi Redmi Note 9 với sự lựa chọn hoàn hảo dành cho những ai đang mong muốn sở hữu một chiếc điện thoại tầm trung có dung lượng pin cao cùng thiết kế sang trọng và khả năng chụp ảnh tốt. Ngày nay, việc sở hữu một chiếc smartphone là điều thiết yếu với mỗi người, giúp người dùng có thể giải quyết cả những công việc mà trước đây chỉ có thể thực hiện trên laptop, mở ra một trai nghiệm thú vị, hiện đại và tiện lợi hơn rất nhiều. \r\n\r\nRedmi Note 9 Pro có thiết kế mặt lưng kính cong 3D và màn hình Full HD+ lên đến 16 triệu điểm ảnh\r\nĐiện thoại Xiaomi này sở hữu thiết kế nguyên khối với mặt lưng kính cong 3D mang đến cho Redmi Note 9 Pro một ngoại hình sang trọng và bắt mắt với các đường nét mềm mại và tinh tế chứ không mang đến cảm giác thô cứng khi cầm nắm.', 1),
(4, 'Xiaomi Redmi 9(3GB- 32GB)', 3100000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/r/e/redmi_9_0002_layer_1.jpg', 'Điện thoại Xiaomi Redmi 9 - Bốn camera cùng màn hình rộng đẹp mắt\r\nXiaomi Redmi 9 được trang bị màn hình phủ trọn mặt trước, vi xử lý 8 nhân 12nm và bốn camera sau chất lượng, đây là chiếc smartphone đáng chú ý trong phân khúc trung cấp, hứa hẹn sẽ là \"siêu phẩm\" của hãng điện thoại nổi tiếng Xiaomi trong năm nay. Ngoài ra, bạn cũng có thể tham khảo thêm Xiaomi Redmi 9A với mức giá hấp dẫn hơn.\r\n\r\nThiết kế bóng bẩy với cảm biến vân tay, màn hình rộng 6.53 inch phủ trọn mặt trước\r\nĐiện thoại Redmi 9 có thiết kế trẻ trung & năng động, sẵn sàng thu hút mọi ánh nhìn. Thân máy và phần khung được làm từ chất liệu nhựa, với mặt lưng có thêm lớp giả kính bóng bẩy & làm nổi bật lên màu sắc của chiếc máy. Mặt lưng cũng được bo cong nhẹ hai bên và bốn góc máy nhằm tạo cảm giác thoải mái khi cầm nắm, cùng cảm biến vân tay được tích hợp phía dưới camera. Ngoài ra, smartphone còn có khả năng chống tóe nước, cho phép người dùng an tâm sư dụng máy dưới điều kiện ẩm ướt.', 1),
(5, 'Samsung Galaxy Note 20', 18400000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/m/i/mint_final.jpg', 'Samsung Note 20 – Màn hình 2K tuyệt hảo và bút S-Pen cho trải nghiệm tiện ích\r\nSau hàng loạt thành công từ những thế hệ Galaxy Note trước, Samsung lại tiếp tục khiến cộng đồng công nghệ phải phát cuồng với siêu phẩm tiếp theo của mình – Samsung Galaxy Note 20, ra mắt cùng với Note 20 Ultra và phiên bản 5G. Siêu phẩm này hứa hẹn sẽ mang đến cho người dùng những trải nghiệm vượt trội hơn, mạnh mẽ hơn với một thiết kế tinh tế, hoàn hảo.\r\n\r\nThiết kế kim loại nguyên khối và mặt lưng kính cường lực tinh tế, sang trọng\r\nCó thể nói, những thiết kế của Samsung luôn khiến cộng đồng đam mê công nghệ phải say mê khi vô cùng tinh tế cùng với những gam màu sang trọng. Sở hữu thiết kế kim loại nguyên khối, mặt lưng được làm từ kính cường lực giúp tăng độ bóng bẩy cho smartphone, mang đến vẻ ngoài đẳng cấp. Note 20 có kiểu dáng mạnh mẽ và có phần nam tính hơn với những góc cạnh vuông vức, mang đến cảm giác cầm tay chắc chắn.', 1),
(6, 'Xiaomi Redmi Note 9 Pro 128GB', 6150000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/_/0/_0000_pms_1589425078.08482488_2.jpg', 'Xiaomi Redmi Note 9 Pro 128GB - Sang trọng, hiệu năng vượt trội\r\nBên cạnh biên bản Note 20 thường, Samsung còn cho ra mắt Note 20 Ultra 5G cho khả năng kết nối dữ liệu cao cùng thiết kế nguyên khối sang trọng, bắt mắt. Đây sẽ là sự lựa chọn hoàn hảo dành cho bạn để sử dụng mà không bị lỗi thời sau thời gian dài ra mắt.\r\n\r\nThiết kế khung nhôm nguyên khối, mặt sau kính cường lực sang trọng\r\nLà một sản phẩm có kích thước màn hình lớn vì vậy Samsung đã trang bị cho Galaxy Note 20 Ultra 5G  với công nghệ kết nối dữ liệu mạnh mẽ cùng thiết kế nguyên khối. Giúp các linh kiện bên trong điện thoại được cố định chắc chắn đảm bảo mọi thứ bên trong luôn được an toàn. Không những vậy khung nhôm tạo trên những đường viền cực kỳ sang trọng và bắt mắt khi nhìn vào.', 1),
(7, 'Samsung Galaxy Note 20 Ultra 5G', 28500000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/y/e/yellow_final_2.jpg', 'Samsung Note 20 Ultra 5G - Sang trọng, hiệu năng vượt trội\r\nBên cạnh biên bản Note 20 thường, Samsung còn cho ra mắt Note 20 Ultra 5G cho khả năng kết nối dữ liệu cao cùng thiết kế nguyên khối sang trọng, bắt mắt. Đây sẽ là sự lựa chọn hoàn hảo dành cho bạn để sử dụng mà không bị lỗi thời sau thời gian dài ra mắt.\r\n\r\nThiết kế khung nhôm nguyên khối, mặt sau kính cường lực sang trọng\r\nLà một sản phẩm có kích thước màn hình lớn vì vậy Samsung đã trang bị cho Galaxy Note 20 Ultra 5G  với công nghệ kết nối dữ liệu mạnh mẽ cùng thiết kế nguyên khối. Giúp các linh kiện bên trong điện thoại được cố định chắc chắn đảm bảo mọi thứ bên trong luôn được an toàn. Không những vậy khung nhôm tạo trên những đường viền cực kỳ sang trọng và bắt mắt khi nhìn vào.', 1),
(8, 'Xiaomi Redmi 9C 3GB - 64GB', 2700000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/r/e/redmi-9c_3__1_2.jpg', 'Xiaomi Redmi 9C 3GB - 64GB - Sử thay đổi toàn diện về một diện mạo mới\r\nLà một chiếc điện thoại tầm trung thuộc dòng Realme series C chiếc Realme C12 được hãng tối ưu đáng kể sự thay đổi về ngoại hình lẫn cấu hình hiệu năng bên trong. Vậy chiếc smartphone này có những nâng cấp gì mới, cấu hình hiệu năng bên trong ra sao?\r\n\r\nThiết kế hợp kim nhôm nguyên khối, màn hình 6.52 inch\r\nMáy được hãng thiết kế với ngoại hình cực kỳ bắt mắt. Cụ thể máy được Realme trang bị một bộ khung vỏ máy làm bằng hợp kim nhôm nguyên khối cực kỳ chắc chắn được CNC và gia công với nhiều màu sắc.\r\n\r\nMặt lưng của chiếc điện thoại này làm bằng nhựa PC chất lượng cao chống bám dính mồ hôi, vân tay. Với kích thước vừa vặn với lòng bàn tay 75.9 x 164.5 x 9.8 mm và chỉ nặng 209 gam bạn có thể cầm chiếc điện thoại Realme C12 một cách dễ dàng.', 1),
(9, 'Realme C12', 2990000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/r/e/realme_c12_0001_realme_c12-removebg-preview.jpg', 'Điện thoại Realme C12 - Sử thay đổi toàn diện về một diện mạo mới\r\nLà một chiếc điện thoại tầm trung thuộc dòng Realme series C chiếc Realme C12 được hãng tối ưu đáng kể sự thay đổi về ngoại hình lẫn cấu hình hiệu năng bên trong. Vậy chiếc smartphone này có những nâng cấp gì mới, cấu hình hiệu năng bên trong ra sao?\r\n\r\nThiết kế hợp kim nhôm nguyên khối, màn hình 6.52 inch\r\nMáy được hãng thiết kế với ngoại hình cực kỳ bắt mắt. Cụ thể máy được Realme trang bị một bộ khung vỏ máy làm bằng hợp kim nhôm nguyên khối cực kỳ chắc chắn được CNC và gia công với nhiều màu sắc.\r\n\r\nMặt lưng của chiếc điện thoại này làm bằng nhựa PC chất lượng cao chống bám dính mồ hôi, vân tay. Với kích thước vừa vặn với lòng bàn tay 75.9 x 164.5 x 9.8 mm và chỉ nặng 209 gam bạn có thể cầm chiếc điện thoại Realme C12 một cách dễ dàng.', 1),
(10, 'Realme C11', 2390000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/r/e/realme_c11_0003_layer_1_2.jpg', 'Điện thoại Realme C11 - Smartphone chơi game tuyệt hảo trong tầm giá\r\nCác fan của dòng smartphone giá rẻ Realme giờ đây có thể sở hữu cho mình sản phẩm mới nhất mang tên Realme C11. Máy được trang bị màn hình lớn, thời lượng pin ấn tượng cùng bộ vi xử lý Helio G35 đầu tiên trên thế giới, đây hứa hẹn sẽ là chiếc smartphone chuyên chơi game tốt nhất trong phân khúc trung cấp giá rẻ. Ngoài ra, bạn cũng có thể tham khảo thêm điện thoại Realme C12 với 3 camera sau.\r\n\r\nMàn hình \"giọt nước\" 6.5 inch HD+ cho trải nghiệm hình ảnh trọn vẹn\r\nRealme C11 sẽ có màn hình thiết kế \"giọt nước\" không còn xa lạ với nhiều người dùng. Tuy phần cằm vẫn còn độ dày đáng kể, hai bên viền bezel đã được thu hẹp đến tối thiểu nhằm tạo trải nghiệm hình ảnh đầy đủ & trọn vẹn nhất. Cạnh dưới của máy vẫn giữ nguyên jack cắm tai nghe 3.5mm, cho phép người dùng tận hưởng âm thanh bằng tai nghe không dây truyền thống.', 1),
(11, 'Realme 6i', 4290000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/s/c/screenshot_11.gif', 'Điện thoại Realme 6i - màn hình giọt nước, 4 camera sau chất lượng\r\nRealme 6i là chiếc điện thoại giá rẻ với cấu hình mạnh. Với thiết kế màn hình tràn viền, hệ thống 4 camera, có cảm biến chính 48MP và đi kèm viên pin “khủng” 5,000 mAh, hỗ trợ sạc nhanh 18W, cùng công nghệ nhiều đột phá. Ngoài ra, bạn cũng có thể tham khảo thêm điện thoại Realme 7i với thiết kế mới, cấu hình mạnh mẽ hơn và hệ thống camera chất lượng hơn.\r\n\r\nCác góc cạnh bo cong nhẹ nhàng, mặt kính cường lực Gorilla Glass 6\r\nVẫn là thiết kế quen thuộc nguyên khối với khung và mặt lưng tương tự Realme 5i với camera xếp dọc bên trái lưng máy. Mặt lưng nhựa với các họa tiết tỏa sáng được làm phẳng, bo cong ở các cạnh máy. Kết hợp với viền bezel cùng hiệu ứng gradient chuyển giúp Realme 6i trở nên rất độc đáo.', 1),
(12, 'Vivo Y50', 5390000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/v/i/vivo-y50-_3.png', 'Điện thoại Vivo Y50 - Nổi bật với cấu hình mạnh trong tầm giá\r\nVừa qua Vivo đã xác nhận sự hiện diện của Vivo Y50 - một trong những chiếc smartphone giá rẻ với cấu hình mạnh. Cụ thể, chiếc smartphone giá rẻ này sẽ có màn hình 6.53 inch với bốn camera sau và chip Snapdragon 665 sẽ mang đến hiệu năng mượt mà cho mọi tác vụ thường ngày.\r\n\r\nMàn hình 6.53 inch thiết kế \"Ultra O\" thời thượng\r\nVivo Y50 được trang bị màn hình có kích thước 6.53 inch với độ phân giải Full HD+ trên nền màu IPS LCD, đáp ứng tốt nhu cầu giải trí như chơi game hoặc xem phim. Tương tự những đời Vivo Y trước, Y50 có thiết kế màn hình \"Ultra O\" thời thượng - màn hình phủ gần như trọn mặt trước và đục lỗ cho camera selfie của máy. Thiết kế cong cạnh 3D góp phần mang đến nét đẹp tinh tế cho điện thoại.', 1),
(13, 'Vivo V19', 7640000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/v/i/vivo-v19-_4.png', 'Điện thoại Vivo V19 – Thiết kế nổi bật, 4 camera chụp đêm cực đỉnh\r\nVivo V19 là smartphone thuộc phân khúc tầm trung được ra mắt vào năm 2020 của thương hiệu Vivo và nhận được sự yêu thích của nhiều người dùng. Điện thoại Vivo này với thiết kế nổi bật và phù hợp với xu hướng hiện đại với màu sắc thời thượng, cấu hình vượt trội cùng với hệ thống camera với chế độ chụp ảnh ban đêm siêu ấn tượng chắc chắn sẽ mang đến cho người dùng nhiều trải nghiệm thú vị.\r\n\r\nThiết kế khung nhựa và mặt lưng kính, màu Bạc thời thượng\r\nVivo V19 có thiết kế hiện đại theo xu hướng của những smartphone cao cấp hiện nay với phần khung nhựa cứng cáp cùng với mặt lưng kính tạo nên độ bóng bẩy, bắt sáng tốt cho vẻ ngoài nổi bật. Điện thoại có kích thước 159.6 x 75 x 8.5 mm cùng với trọng lượng chỉ 186.5g vô cùng gọn nhẹ mang đến sự thoải mái khi cầm cũng như gọn gàng khi cho vào túi.', 1),
(14, 'iPhone 11 Chính hãng', 18000000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/_/0/_0004_layer_5.jpg', 'iPhone 11 chính hãng VN/A – Chiếc điện thoại nhiều màu sắc, camera nâng cấp\r\niPhone 11 là model có nhiều màu sắc nhất và có giá rẻ nhất trong bộ 3 iPhone 11 series được Apple ra mắt trong năm 2019. Bên cạnh đó, cấu hình iPhone 11 cũng được nâng cấp đặc biệt về cụm camera sau và Face ID, viên pin dung lượng lớn hơn.\r\n\r\nĐa dạng sự lựa chọn với 6 phiên bản màu sắc\r\nĐiểm nổi bật của iPhone 11 2019 đó là bên cạnh hai phiên bản đen và trắng quen thuộc thì máy còn có thêm bốn phiên bản khác đó là tím, vàng, xanh lá, đỏ. Với tất cả các phiên bản, bao gồm cả điện thoại iPhone 12 sắp ra mắt thì Apple đều thiết kế cạnh bên trùng màu với thân máy, tạo nên một thể thống nhất.', 1),
(15, 'iPhone 11 Pro Max Chính hãng', 27200000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/i/p/iphone-11-pro-max_4_.jpg', 'iPhone 11 Pro Max – Bộ ba camera sau chụp ảnh đỉnh cao\r\nRa mắt cùng với iPhone 11 và 11 Pro là iPhone 11 Pro Max, đây mẫu smartphone cao cấp nhất của iPhone 11 Series được ra mắt năm 2019 và sắp tới là điện thoại iPhone 12 trong năm 2020. Với thiết kế cao cấp, hệ thống camera 3 camera cùng cấu hình siêu mạnh mẽ thì đây chính là một chiếc smartphone đáp ứng mọi trải nghiệm của người dùng.\r\n\r\nKích thước to hơn với chất liệu thép không gỉ bền bỉ\r\nĐiện thoại có thiết kế tương tự như iPhone 11 Pro nhưng kích thước thì to hơn với kích thước màn hình 6.5 inch và toàn bộ máy có kích thước 158 x 77.8 x 8.1 mm. Thiết kế không có nhiều thay đổi trừ hệ thống camera sau được nâng cấp thành 3 camera. Màn hình tai thỏ vẫn được giữ nguyên và chất liệu thép không gỉ giúp 11 Pro Max bền bỉ hơn.', 1),
(16, 'ASUS ROG Phone 3 Chính hãng', 22990000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/r/o/rog_3.jpg', 'Điện thoại Asus ROG Phone 3 – Smartphone chuyên game sức mạnh vô đối\r\nROG Phone 3 mang trên mình những công nghệ tiên tiến và thiết kế hầm hố nhất. Với sức mạnh vô đối cùng thời lượng pin khủng, chiếc smartphone gaming của Asus mới ra mắt đã để lại ấn tượng sâu sắc trong lòng người hâm mộ.\r\n\r\nĐường nét tinh xảo, mặt lưng được bo cong mềm mại\r\nVề thiết kế, điện thoại sở hữu một vẻ ngoài đầy thu hút với các đường cắt tinh xảo và độc đáo. Vẫn giữ được sự hầm hố nhưng bề mặt lưng của phiên bản này phẳng hơn, đẹp mắt hơn. Ở mặt lưng máy chúng ta sẽ thấy cụm 3 camera nằm ở góc trên bên trái và có đèn LED kép, logo ROG.', 1),
(17, 'Apple iPhone XR 64GB Chính hãng', 12990000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/i/p/iphone-xr_5_.jpg', 'Điện thoại iPhone XR - Sang trọng, trẻ trung với nhiều màu sắc\r\nĐược ra mắt cùng Apple iPhone XS và XS Max, iPhone XR không chỉ được thừa kế những tính năng đặc trưng nổi trội của người tiền nhiệm iPhone X được ra mắt một năm trước đó và còn có những cải tiến nhằm mang lại trải nghiệm mới lạ và thú vị cho người dùng.\r\n\r\niPhone XR chính hãng (VN/A) là gì? Vì sao khách hàng nên chọn mã VN/A\r\nĐầu tiên, VN/A là mã trên sản phẩm Apple phân phối trực tiếp cho các đại lý ủy quyền Apple tại Việt Nam và iPhone XR 64GB chính hãng (VN/A) là hàng chính hãng do Apple sản xuất theo tiêu chuẩn của thị trường Việt Nam.', 1),
(18, 'iPhone 11 128GB Chính hãng', 20000000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/i/p/iphone-11_3_.jpg', 'iPhone 11 128GB Chính hãng - Sang trọng, trẻ trung với nhiều màu sắc\r\nĐược ra mắt cùng Apple iPhone XS và XS Max, iPhone XR không chỉ được thừa kế những tính năng đặc trưng nổi trội của người tiền nhiệm iPhone X được ra mắt một năm trước đó và còn có những cải tiến nhằm mang lại trải nghiệm mới lạ và thú vị cho người dùng.\r\n\r\niPhone XR chính hãng (VN/A) là gì? Vì sao khách hàng nên chọn mã VN/A\r\nĐầu tiên, VN/A là mã trên sản phẩm Apple phân phối trực tiếp cho các đại lý ủy quyền Apple tại Việt Nam và iPhone XR 64GB chính hãng (VN/A) là hàng chính hãng do Apple sản xuất theo tiêu chuẩn của thị trường Việt Nam.', 1),
(19, 'Samsung Galaxy A71', 8350000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/a/7/a71_bac_3.jpg', 'Samsung A71 – Smartphone tầm trung của Samsung\r\nSamsung Galaxy A71 sẽ là điện thoại giá cả phải chăng của Samsung với mục đích tiếp cận đối tượng rộng hơn. Samsung A71 là sản phẩm thuộc series Samsung Galaxy A với màn hình đục lỗ, cấu hình mạnh mẽ, cụm bốn camera sau chất lượng cao và cùng nhiều công nghệ thời thượng.\r\n\r\nSau Galaxy A51 và A71, rất có thể Galaxy A01 sẽ là sản phẩm tiếp theo thuộc dòng Galaxy A 2020 được Samsung trình làng trong thời gian sắp tới.\r\n\r\nMàn hình đục lỗ 6,7 inch, Full HD với tấm nền Super AMOLED\r\nGalaxy A71 sở hữu màn hình Super AMOLED Plus 6,7 inch. Có độ phân giải Full HD 1080 x 2400 pixel, 393ppi. Máy cũng được trang bị đầu đọc dấu vân tay dưới màn hình giống như nhiều mẫu smartphone của Samsung đã ra mắt gần đây với tốc độ nhận diện rất nhanh. Cùng với đó là chức năng mở khóa bằng nhận diện khuôn mặt.', 1),
(20, 'iPhone 11 Pro Chính hãng', 24000000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/i/p/iphone-11-pro_4_.jpg', 'iPhone 11 Pro - Siêu phẩm 3 camera chụp ảnh chuyên nghiệp\r\niPhone 11 Pro là 1 trong 3 mẫu smartphone mới nhất của iPhone 11 series được Apple ra mắt vào năm 2019, bên cạnh iPhone 11 và iPhone 11 Pro Max. Bộ ba siêu phẩm này đều tập trung về nâng cấp phần cứng và hiệu năng. Đặc biệt, chiếc iPhone 11 Pro có đến 3 camera có các chứng năng chụp hình và quay phim chuyên nghiệp đỉnh cao.\r\n\r\nThiết kế thép nguyên khối với mặt lưng kính mờ và màn hình 5.8 inches sắc nét\r\nĐiều đáng chú ý về việc nguyên liệu được sử dụng làm điện thoại của Apple là loại thép chống gỉ với độ bền cực tốt, mà lại cho ánh sáng bóng loáng, tinh tế và sang trọng. Mặt lưng kính trên iPhone 11 Pro nay cũng được cải tiến làm mờ đi chứ không để bóng như trên iPhone Xs nhằm giảm việc bám mồ hôi và vân tay, loại bỏ trầy xước.', 1),
(21, 'Apple iPhone 8 Plus 128GB Chính hãng', 13000000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/i/p/iphone-8-plus_4_.jpg', 'Điện thoại iPhone 8 Plus 128GB chính hãng – Bộ nhớ lưu trữ lớn, camera kép nâng cấp trải nghiệm\r\nKế thừa sự thành công của iPhone 7/7 Plus, Apple lại tiếp tục làm cộng đồng yêu công nghệ phải chú ý khi cho ra mắt mẫu điện thoại iPhone 12 và kế tiếp của họ - iPhone 8 Plus 128GB. iPhone 8 Plus 128GB sở hữu thiết kế đẳng cấp với mặt lưng làm từ kính hoàn toàn mới lạ, độc đáo và sang trọng hơn người anh em tiền nhiệm. Bên cạnh đó, iPhone 8 Plus cũng có nhiều nâng cấp từ camera, hiệu năng,… để mang đến cho người dùng những trải nghiệm đỉnh cao hơn.\r\n\r\nBộ nhớ trong 128GB lưu trữ nhiều tập tin dữ liệu\r\nBộ nhớ trong dung lượng đến 128GB chính là một phần sức mạnh của smartphone. Với mức dung lượng này, bạn có thể lưu trữ đến hàng nghìn tập tin bài hát, hình ảnh, video, cài đặt các ứng dụng một cách thoải mái. Nếu nhu cầu lưu trữ thấp hơn, bạn có thể tham khảo thêm điện thoại iPhone 8 Plus 64GB VN/A hoặc iPhone 8 Plus 64GB nhập khẩu.', 1),
(22, 'Samsung Galaxy Note 10+ (Plus)', 16300000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/n/o/note_10_plus_xanh.jpg', 'Samsung Note 10 Plus – Màn hình lớn cho trải nghiệm tuyệt đỉnh, S-Pen tiện dụng\r\nLà phiên bản nâng cấp đáng giá ra đời cùng thời điểm với Samsung Galaxy Note 10, Samsung Galaxy Note 10 Plus là sự lựa chọn tuyệt vời cho người dùng đam mê công nghệ có nhu cầu sở hữu một chiếc điện thoại hoàn hảo về mọi mặt. Với Note 10 Plus, Samsung đã thật sự mang đến một chiếc điện thoại có sức mạnh vượt trội, đáp ứng toàn diện các nhu cầu về làm việc và giải trí của người dùng. Ngoài ra, bạn có thể tham khảo thêm Galaxy Note 20 sắp được ra mắt.\r\n\r\nSamsung Note 10 Plus có thiết kế vuông vắn, chất liệu kim loại kết hợp thủy tinh cao cấp\r\nGalaxy Note 10 Plus tạo nên ấn tượng đặc biệt từ ban đầu bởi vẻ ngoài đẳng cấp. Kế thừa trọn vẹn tinh hoa thiết kế của dòng sản phẩm Galaxy Note nhà Samsung, Note 10 Plus có ngoại hình vuông vứt đầy mạnh mẽ và tinh tế. Viền màn hình cực kỳ mỏng cùng với độ dày mảnh mai không kém, giúp Note 10 Plus dùng có kích thước lớn nhưng vẫn giữ được sự thanh thoát, sang trọng.', 1),
(23, 'Samsung Galaxy Note 10 Lite', 10650000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/2/0/2026427.png', 'Samsung Note 10 Lite - Phiên bản nhỏ gọn, đa năng của siêu phẩm Note 10\r\nGalaxy Note 10 Lite (ra mắt cùng với Galaxy S10 Lite) là phiên bản nhỏ gọn hơn, giá rẻ hơn bộ đôi siêu phẩm Note 10 / Note 10+ nhưng vẫn giữ nguyên những tinh hoa của người tiền nhiệm nhưng với mức giá hấp dẫn hơn. Mặc dù điện thoại Samsung Note 20 sắp ra mắt nhưng đây vẫn là sự lựa chọn hợp lý ở thời điểm hiện tại. \r\n\r\nSamsung Note 10 Lite có cấu hình như thế nào\r\nTrong thuật ngữ công nghệ, chữ \"lite\" đại diện cho \"light\", nghĩa là phiên bản nhẹ hơn, được thu nhỏ để vận hành ổn định mà không bị giật. Về cơ bản, bất kỳ thiết bị nào có chữ \"Lite\" trong tên sản phẩm đều là phiên bản nhỏ hơn, vận hành nhẹ hơn so với thiết bị gốc được ra mắt trước đó.', 1),
(24, 'Vsmart Joy 3 4GB', 2590000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/j/o/joy-3-4g-tim.jpg', 'Điện thoại Vsmart Joy 3 4GB là một trong những sản phẩm bán chạy tại Cellphones. Mua Vsmart Joy 3 4GB ngay để nhận giá tốt nhất cùng nhiều ưu đãi hấp dẫn. Ngoài ra, bạn cũng có thể tham khảo thêm Vsmart Joy 3 2GB.', 1),
(25, 'iPhone 11 Pro Max 256GB Chính hãng', 31000000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/i/p/iphone-11-pro-max_1__2.jpg', 'Bên cạnh phiên bản 256GB bộ nhớ trong, bạn cũng có thể lựa chọn cho mình điện thoại iPhone 11 Pro Max 64GB nếu nhu cầu lưu trữ của bạn không quá nhiều.', 1),
(26, 'Samsung Galaxy Note 10', 13800000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/6/3/637148757998466143_ss-note-10-do-1.png', 'Điện thoại Samsung Galaxy Note 10 – Trải nghiệm máy tính trong chính smartphone của bạn\r\nVới hàng loạt những siêu phẩm từng tung ra thị trường, điện thoại Samsung lại một lần nữa làm cộng đồng người yêu công nghệ phải đứng ngồi không yên khi trình làng bộ đôi Samsung Galaxy Note 10 và Note 10 Plus mang đến những trải nghiệm tuyệt đỉnh như máy tính ngay từ chính chiếc smartphone của bạn, giúp bạn có thể làm mọi thứ chỉ bằng một chiếc điện thoại. Ngoài ra, bạn cũng có thể tham khảo phiên bản rút gọn với giá bán phải chăng hơn là Samsung Note 10 Plus.\r\n\r\nMặc dù Samsung Galaxy Note 20 sắp được ra mắt nhưng hiện tại Note 10 vẫn đang là sự lựa chọn hợp lý với giá tốt đi kèm nhiều tính năng cao cấp.\r\n\r\nThiết kế khung thép không gỉ và thủy tinh cao cấp cùng màu sắc thời trang, hiện đại\r\nSamsung Galaxy Note 10 mang phong cách thiết kế vuông vắn, kích thước 71.8 x 151 mm và độ mỏng chỉ 7.9mm. Với khung điện thoại được làm từ chất liệu thép không gỉ kết hợp với thủy tinh cao cấp được đánh bóng cho khả năng bắt sáng tạo nên ánh quang cùng lớp kính cường lực Gorilla 6 mang đến sự bảo vệ vừng chắc cho Samsung Galaxy Note. Các chi tiết, đường nét được gia công tinh tế, tỉ mỉ mang đến sự hoàn hảo cho vẻ ngoài của chiếc smartphone siêu phẩm này. Khả năng kháng bụi, kháng nước chuẩn IP68 mang đến sự bền bỉ, bảo vệ điện thoại khỏi các hư hại do bụi và nước gây ra.', 1),
(27, 'Apple iPhone 7 Plus 128GB Chính hãng', 10000000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/i/p/iphone-7-plus_5_.jpg', 'iPhone 7 Plus 128Gb\r\niPhone 7 Plus 128GB với thiết kế không quá nhiều thay đổi, vẫn bảo tồn vẻ đẹp truyền thống từ thời iPhone 6 Plus. Tuy nhiên, phần cứng iPhone 7 Plus đã được nâng cấp đáng kể như camera kép cùng cấu hình cực mạnh.\r\n\r\nTại sao iPhone 7 Plus 128Gb VN/A là sự lựa chọn tốt nhất\r\nĐây là những chiếc iPhone 7 Plus 128GB được sản xuất dành riêng cho thị trường Việt Nam (mã VN/A) được CellphoneS phân phối dưới hình thức máy mới, chính hãng 100%, thích hợp cho người có nhu cầu tìm mua 1 chiếc điện thoại để sử dụng lâu dài do nền tảng hệ điều hành iOS mang lại.', 1),
(28, 'iPhone SE 2020 Chính hãng', 11200000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/i/p/iphone-se-2020_3_.jpg', 'iPhone SE 2020 – Phiên bản nâng cấp của iPhone 8 với hiệu năng vượt trội hơn\r\nVới hàng loạt thành công từ các siêu phẩm iPhone 11 thì Apple lại tiếp tục tung ra chiếc iPhone SE 2020 (hay iPhone 9) – bản nâng cấp của iPhone SE ra mắt cách đây 3 năm – khiến người hâm mộ và các tín đồ công nghệ tiếp tục phát cuồng. Đây chính là chiếc smartphone được mong chờ nhất những năm qua và đến nay cộng đồng người yêu công nghệ mới được chiêm ngưỡng vẻ đẹp của chiếc smartphone này.\r\n\r\nThiết kế kim loại nguyên khối, mặt kính cường lực và các góc được bo tròn nhiều hơn\r\nKhác với phiên bản iPhone 5 SE 2016 trước, iPhone SE 2 sẽ có thiết kế khá giống với iPhone 8 nghĩa là chiếc smartphone này sẽ không còn phần khung viền vát phẳng nữa mà sẽ được bo tròn nhiều hơn. Kiểu dáng đơn giản nhưng hài hòa, tinh tế trong từng đường nét và thiết kế nhôm kính mang đến sự bền bỉ, sang trọng.', 1),
(29, 'Vsmart Live 4', 4790000, 'https://cdn.cellphones.com.vn/media/catalog/product/cache/7/image/9df78eab33525d08d6e5fb8d27136e95/v/s/vsmart-live-_4_1_.jpg', 'Điện thoại Vsmart Live 4 - Cấu hình khủng, camera ấn tượng\r\nTin tức về thế hệ tiếp theo của Vsmart Live khiến cho các tín đồ công nghệ đứng ngồi không yên. Mới đây, những cấu hình của Vsmart Live 4 đã được lộ diện, với màn hình \"đục lỗ\" kích thước lớn, cụm camera AI 4 ống kính và cảm biến vân tay mặt lưng, chắc chắn sẽ là chiếc smartphone nổi bật nhất trong phân khúc trung cấp.\r\n\r\nMàn hình \"đục lỗ\" Full HD+ kích thước lớn, nhiều lựa chọn màu sắc\r\nLive 4 sẽ có thay đổi lớn trước tiên là về màn hình. Thay vì thiết kế \"giọt nước\" hoặc \"vô cực\" như trước, điện thoại Vsmart này hướng đến kiểu dáng màn hình \"đục lỗ\" tương tự các dòng smartphone cao cấp hiện nay. Màn hình này sẽ có kích thước lớn, sử dụng nền màu LKTC và có độ phân giải Full HD+ cho hình ảnh sắc nét & chân thực.', 1),
(30, 'Laptop LG Gram 2020 14ZD90N-V.AX53A5 - Hàng chính hãng', 24490000, 'https://laptop88.vn/media/product/5122_02_______y_lg_gram_2020___campaign_900x900_02.jpg', 'Laptop LG Gram siêu nhẹ, siêu bền bỉ cứng cáp. Cấu hình cao, màn đẹp, giá cực tốt\r\n14\" Trắng\r\n14\" Xám\r\n14\" Xám - Win 10\r\n15.6\" Trắng\r\n15.6\" Xám - Win10\r\n17\" Xám - Win10 Plus\r\n15\" Xám - Win 10 - i5 8265U\r\nCPU:\r\nIntel Core i5 -1035G7\r\nRAM:\r\nRAM 8GB DDR4\r\nỔ cứng:\r\nSSD 256GB NVMe\r\nCard đồ họa:\r\nCard onboard Intel® Iris® Plus Graphics\r\nMàn hình:\r\n14 Inch Full HD\r\n✅Bảo hành 12 tháng chính hãng - Xem chính sách\r\n\r\n✅Giá ở trên đã bao gồm 10% VAT\r\n\r\n✅ MIỄN PHÍ GIAO HÀNG TẬN NHÀ\r\n\r\n- Với đơn hàng < 4.000.000 đồng: Miễn phí giao hàng cho đơn hàng < 5km tính từ cửa hàng Laptop88 gần nhất\r\n\r\n- Với đơn hàng > 4.000.000 đồng: Miễn phí giao hàng (khách hàng chịu phí bảo hiểm hàng hóa nếu có)', 2),
(31, 'Laptop Asus Pro P1440FA-FA0674T - Intel Core i3', 7990000, 'https://laptop88.vn/media/product/5124____nh_n___i_b___t_th__ng_6_02.png', 'màn Full HD, SIÊU BỀN đạt tiêu chuẩn quân sự Mỹ, có ổ DVD học tiếng Anh, bảo hành 2 năm chính hãng\r\nAsus X509 - Core i5 8265U + Geforce MX230\r\nAsus P1440FA - Core i3 8145U\r\nHP Pavilion 15 - Core i3 8145U\r\nAcer Aspire 3 - AMD Ryzen 3\r\nAspire 3 - Core i5 1035G1 (Gen 10)\r\nAspire 5 - Core i3 1005G1 (Gen 10)\r\nCPU:\r\nIntel Core i3 - 8145U\r\nBộ nhớ:\r\nRAM 4GB DDR4 + SSD 180GB(*)\r\nRAM 8GB DDR4 + SSD 240GB(*)\r\nCard đồ họa:\r\nCard onboard Intel UHD Graphics 620\r\nMàn hình:\r\n14 Inch Full HD\r\n✅Bảo hành 24 tháng chính hãng - Xem chính sách\r\n\r\n✅Giá ở trên đã bao gồm 10% VAT\r\n\r\n✅MIỄN PHÍ GIAO HÀNG \r\n\r\n- Với đơn hàng < 4.000.000 đồng: Miễn phí giao hàng cho đơn hàng < 5km tính từ cửa hàng Laptop88 gần nhất\r\n\r\n- Với đơn hàng > 4.000.000 đồng: Miễn phí giao hàng (khách hàng chịu phí bảo hiểm hàng hóa nếu có)', 2),
(32, 'Laptop LG Gram 2020 14Z90N-V.AR52A5 - Hàng chính hãng', 26490000, 'https://laptop88.vn/media/product/5121_14z90n_v_ar52a5.png', '✔Windows 10 bản quyền\r\n14\" Trắng\r\n14\" Xám\r\n14\" Xám - Win 10\r\n15.6\" Trắng\r\n15.6\" Xám - Win10\r\n17\" Xám - Win10 Plus\r\n15\" Xám - Win 10 - i5 8265U\r\nCPU:\r\nIntel Core i5-1035G7\r\nRAM:\r\nRAM 8GB DDR4\r\nỔ cứng:\r\nSSD 256GB NVMe\r\nCard đồ họa:\r\nCard onboard Intel® Iris® Plus Graphics\r\nMàn hình:\r\n14 Inch Full HD\r\n✅Bảo hành 12 tháng chính hãng - Xem chính sách\r\n\r\n✅Giá ở trên đã bao gồm 10% VAT\r\n\r\n \r\n\r\n✅ MIỄN PHÍ GIAO HÀNG TẬN NHÀ\r\n\r\n- Với đơn hàng < 4.000.000 đồng: Miễn phí giao hàng cho đơn hàng < 5km tính từ cửa hàng Laptop88 gần nhất\r\n\r\n- Với đơn hàng > 4.000.000 đồng: Miễn phí giao hàng (khách hàng chịu phí bảo hiểm hàng hóa nếu có)', 2),
(33, 'Laptop Acer Aspire 3 A315-56-59XY - Intel Core i5', 12690000, 'https://laptop88.vn/media/product/5149____nh_n___i_b___t_th__ng_6_03.png', 'Laptop cấu hình cao, giá rẻ nhất thị trường. Chip i5 đời 10, màn 15\" FHD, SSD 256 NVMe có sẵn. Wifi mạnh, tiện di chuyển\r\nAsus X509 - Core i5 8265U + Geforce MX230\r\nAsus P1440FA - Core i3 8145U\r\nHP Pavilion 15 - Core i3 8145U\r\nAcer Aspire 3 - AMD Ryzen 3\r\nAspire 3 - Core i5 1035G1 (Gen 10)\r\nAspire 5 - Core i3 1005G1 (Gen 10)\r\nCPU:\r\nIntel Core i5-1035G1\r\nRAM:\r\nRAM 8GB DDR4 (4GB sẵn + 4GB quà tặng)\r\nỔ cứng:\r\nSSD 256GB NVMe\r\nCard đồ họa:\r\nCard Intel UHD 620\r\nMàn hình:\r\n15.6 Inch Full HD\r\n✅ Bảo hành chính hãng Acer Việt Nam 12 tháng\r\n\r\n✅Window 10 bản quyền theo máy\r\n\r\n✅ MIỄN PHÍ GIAO HÀNG TẬN NHÀ\r\n\r\n- Với đơn hàng < 4.000.000 đồng: Miễn phí giao hàng cho đơn hàng < 5km tính từ cửa hàng Laptop88 gần nhất\r\n\r\n- Với đơn hàng > 4.000.000 đồng: Miễn phí giao hàng (khách hàng chịu phí bảo hiểm hàng hóa nếu có)', 2),
(34, 'Laptop HP Pavilion 15-cs2032TU 6YZ04PA - Intel Core i3', 11290000, 'https://laptop88.vn/media/product/4691_hp_15_cs2000tu_3.jpg', 'Bảo hành chính hãng 12 tháng. Vỏ kim loại cao cấp chắc chắn, màn 15 inch chất lượng hiển thị tốt. Thiết kế sang trọng, cấu hình đủ làm mượt mọi tác vụ\r\nAsus X509 - Core i5 8265U + Geforce MX230\r\nAsus P1440FA - Core i3 8145U\r\nHP Pavilion 15 - Core i3 8145U\r\nAcer Aspire 3 - AMD Ryzen 3\r\nAspire 3 - Core i5 1035G1 (Gen 10)\r\nAspire 5 - Core i3 1005G1 (Gen 10)\r\nCPU:\r\nIntel Core i3 8145U\r\nRAM:\r\n8GB DDR4 (4GB sẵn + 4GB quà tặng)\r\nỔ cứng:\r\nHDD 1TB + SSD 180GB (quà tặng)\r\nCard đồ họa:\r\nIntel HD 620\r\nMàn hình:\r\n15.6 Inch Full HD\r\n✅Bảo hành chính hãng HP 12 tháng - Xem chính sách\r\n\r\n✅Giá ở trên đã bao gồm 10% VAT\r\n\r\n✅ MIỄN PHÍ GIAO HÀNG TẬN NHÀ\r\n\r\n- Với đơn hàng < 4.000.000 đồng: Miễn phí giao hàng cho đơn hàng < 5km tính từ cửa hàng Laptop88 gần nhất\r\n\r\n- Với đơn hàng > 4.000.000 đồng: Miễn phí giao hàng (khách hàng chịu phí bảo hiểm hàng hóa nếu có)', 2),
(35, 'Laptop HP Pavilion X360 14-dh0104TU - Intel Core i5', 14490000, 'https://laptop88.vn/media/product/4714_hp_pavilion_x360_14_dh0104tu_5.jpg', 'Laptop 2 trong 1 màn hình cảm ứng. Cấu hình cao chip đời 8. Vỏ kim loại sang trọng, bền bỉ chắc chắn. GIÁ TỐT NHẤT THỊ TRƯỜNG\r\nHP X360 14-dh0104TU - i5\r\nHP X360 14-dh1137TU - i3\r\nHP X360 14-dh0103TU - i3\r\nHP X360 14-cd1018TU - i3\r\nCPU:\r\nIntel Core i5 8265U\r\nRAM:\r\n8GB DDR4 (4GB sẵn + 4GB quà tặng)\r\nỔ cứng:\r\nHDD 1TB + SSD 180GB\r\nCard đồ họa:\r\nIntel HD Graphics 620\r\nMàn hình:\r\n14 Inch Full HD\r\n✅Bảo hành chính hãng HP Việt Nam 12 tháng - Xem chính sách\r\n\r\n✅Giá ở trên đã bao gồm 10% VAT\r\n\r\n✅ MIỄN PHÍ GIAO HÀNG TẬN NHÀ\r\n\r\n \r\n\r\n- Với đơn hàng < 4.000.000 đồng: Miễn phí giao hàng cho đơn hàng < 5km tính từ cửa hàng Laptop88 gần nhất\r\n\r\n \r\n\r\n- Với đơn hàng > 4.000.000 đồng: Miễn phí giao hàng (khách hàng chịu phí bảo hiểm hàng hóa nếu có)', 2),
(36, 'Laptop LG Gram 2020 14ZD90N-V.AX55A5 - Hàng chính hãng', 26490000, 'https://laptop88.vn/media/product/5123_14zd90n_v_ax55a5.png', '\r\n14\" Trắng\r\n14\" Xám\r\n14\" Xám - Win 10\r\n15.6\" Trắng\r\n15.6\" Xám - Win10\r\n17\" Xám - Win10 Plus\r\n15\" Xám - Win 10 - i5 8265U\r\nCPU:\r\nIntel Core i5 -1035G7\r\nRAM:\r\nRAM 8GB DDR4\r\nỔ cứng:\r\nSSD 512GB NVMe\r\nCard đồ họa:\r\nCard onboard Intel® Iris® Plus Graphics\r\nMàn hình:\r\n14 Inch Full HD\r\n✅Bảo hành 12 tháng chính hãng - Xem chính sách\r\n\r\n✅Giá ở trên đã bao gồm 10% VAT\r\n\r\n✅ MIỄN PHÍ GIAO HÀNG TẬN NHÀ\r\n\r\n- Với đơn hàng < 4.000.000 đồng: Miễn phí giao hàng cho đơn hàng < 5km tính từ cửa hàng Laptop88 gần nhất\r\n\r\n- Với đơn hàng > 4.000.000 đồng: Miễn phí giao hàng (khách hàng chịu phí bảo hiểm hàng hóa nếu có)', 2),
(37, 'Laptop LG Gram 2020 15Z90N-V.AR55A5 - Hàng chính hãng', 32490000, 'https://laptop88.vn/media/product/5126_15z90n_v_ar55a5.png', 'Laptop LG Gram siêu nhẹ, siêu bền bỉ cứng cáp. Cấu hình cao, màn đẹp, giá cực tốt\r\n✔Windows 10 bản quyền\r\n14\" Trắng\r\n14\" Xám\r\n14\" Xám - Win 10\r\n15.6\" Trắng\r\n15.6\" Xám - Win10\r\n17\" Xám - Win10 Plus\r\n15\" Xám - Win 10 - i5 8265U\r\nCPU:\r\nIntel Core i5 - 1035G7\r\nRAM:\r\nRAM 8GB DDR4\r\nỔ cứng:\r\nSSD 512GB NVMe\r\nCard đồ họa:\r\nCard onboard Intel Iris Plus Graphics\r\nMàn hình:\r\n15.6 Inch Full HD\r\n✅Bảo hành 12 tháng chính hãng - Xem chính sách\r\n\r\n✅Giá ở trên đã bao gồm 10% VAT\r\n\r\n \r\n\r\n✅ MIỄN PHÍ GIAO HÀNG TẬN NHÀ\r\n\r\n- Với đơn hàng < 4.000.000 đồng: Miễn phí giao hàng cho đơn hàng < 5km tính từ cửa hàng Laptop88 gần nhất\r\n\r\n- Với đơn hàng > 4.000.000 đồng: Miễn phí giao hàng (khách hàng chịu phí bảo hiểm hàng hóa nếu có)', 2),
(38, 'Laptop LG Gram 2020 15ZD90N-V.AX56A5 - Hàng chính hãng', 27490000, 'https://laptop88.vn/media/product/5127_15zd90n_v_ax56a5.png', 'Laptop LG Gram siêu nhẹ, siêu bền bỉ cứng cáp. Cấu hình cao, màn đẹp, giá cực tốt\r\n14\" Trắng\r\n14\" Xám\r\n14\" Xám - Win 10\r\n15.6\" Trắng\r\n15.6\" Xám - Win10\r\n17\" Xám - Win10 Plus\r\n15\" Xám - Win 10 - i5 8265U\r\nCPU:\r\nIntel Core i5 - 1035G7\r\nRAM:\r\nRAM 8GB DDR4\r\nỔ cứng:\r\nSSD NVMe 512GB\r\nCard đồ họa:\r\nCard onboard Intel® Iris® Plus\r\nMàn hình:\r\n15.6 Inch Full HD\r\n✅Bảo hành 12 tháng chính hãng - Xem chính sách\r\n\r\n✅Giá ở trên đã bao gồm 10% VAT\r\n\r\n✅ MIỄN PHÍ GIAO HÀNG TẬN NHÀ\r\n\r\n- Với đơn hàng < 4.000.000 đồng: Miễn phí giao hàng cho đơn hàng < 5km tính từ cửa hàng Laptop88 gần nhất\r\n\r\n- Với đơn hàng > 4.000.000 đồng: Miễn phí giao hàng (khách hàng chịu phí bảo hiểm hàng hóa nếu có)', 2),
(39, 'Laptop Asus M413IA-EK338T - AMD Ryzen 5', 14990000, 'https://laptop88.vn/media/product/5443_asus_m413ia_ek338t_2.png', 'Laptop thời trang mỏng nhẹ, vỏ kim loại\r\nChip ryzen 5 4500U, màn hình Full HD IPS\r\nBảo hành 24 tháng chính hãng Asus\r\nM533 Ryzen 5\r\nM533 Ryzen 7\r\nM433 Ryzen 5\r\nM433 Ryzen 7\r\nM413 Ryzen 5\r\nCPU:\r\nAMD Ryzen 5 4500U\r\nRAM:\r\nRAM 8GB DDR4\r\nỔ cứng:\r\nSSD 512GB NVMe\r\nCard đồ họa:\r\nCard AMD Vega 6\r\nMàn hình:\r\n14 Inch Full HD\r\n✅Bảo hành 24 tháng chính hãng - Xem chính sách\r\n\r\n✅Windows 10 bản quyền theo máy\r\n\r\n✅ MIỄN PHÍ GIAO HÀNG TẬN NHÀ\r\n\r\n- Với đơn hàng < 4.000.000 đồng: Miễn phí giao hàng cho đơn hàng < 5km tính từ cửa hàng Laptop88 gần nhất\r\n\r\n- Với đơn hàng > 4.000.000 đồng: Miễn phí giao hàng (khách hàng chịu phí bảo hiểm hàng hóa nếu có)', 2);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `category`
--
ALTER TABLE `category`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `category`
--
ALTER TABLE `category`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `product`
--
ALTER TABLE `product`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=40;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
